### ISSUE TITLE
No typing in collection_get return like in get returns

### ISSUE THREAD

**Issue by yanndinendal** [mardiros/blacksmith#28]
When using `.get`, the response gets the correct type passed to the SyncClient generic type:

```py
        api: SyncClient[Any, PricesGetReturn] = self.get_client("shs")
        response = api.prices.get(
            {
                "country": country,
                "currency": currency,
            }
        ).response  # response: PricesGetReturn
        print(response.prices)  # auto-completed
```

but when using `.collection_get`, no typing/autocompletion is available:

```py
        api: SyncClient[PricesGetReturn, Any] = self.get_client("shs")
        response = api.prices.collection_get(
            {
                "country": country,
                "currency": currency,
            }
        ).response  # response: AbstractCollectionParser
        print(response.json["prices"])  # no auto-completion
```

Is there a reason why collection returns don't use `ResponseBox` or is it just not yet implemented like this?

**Comment by mardiros** [comment]
It is because this is not supposed to be consumed this way.

Actually the ResponseBox is wrapping a type and the AbstractCollectionParser too.
My point of view is that there is no reason to wrap abscract collection parser, by the way, you can still implement your own collection parser if it has to be customized.

Now, let me explain how it is supposed to be consumed.


```
api: SyncClient[PartialPrice, Price] = self.get_client("shs")
# The first type (PartialPrice) is the collection type, prefixed "partial"  by convention in blacksmith.
# Usually a collection does not return all propeties, so it is a partial object.

prices = api.prices.collection_get(
            {
                "country": country,
                "currency": currency,
            }
)

for price in prices:
  print (price)  # auto completion should works here.

```

If it's works for you, you can close the issue. Otherwise I will take a closer look. Let me now !

**Comment by mardiros** [comment]
Yes you are right. The AbstractCollectionParse is here to deserialize item per item for these case.

Or maybe, the API you consume should be fix upstream...
